Truncate obuf files
Paradigm4/shim pull request #126
Opened 2023-01-23 17:29 UTC by jwimberl

Truncate obuf files to reduce /dev/shm usage when reading query results are complete, with subsequent read calls return HTTP 410 errors:

 * Truncate output after calls to /read_bytes and /read_lines with n=0
 * Truncate output after calls to /read_bytes and /read_lines with n>0 in which the obuf is at EOF (and not after the calls which return the final bytes/lines)

Adds endpoints /read_bytes_weak and /read_lines_weak that preserve original behavior
Adjusts unit tests as necessary

2023-01-23 23:39 UTC, rvernica requested changes
Generally looks good. See my two line comments.

2023-01-23 23:39 UTC, rvernica commented on src/shim.c
> -  free (lbuf);
Is this no longer needed?

2023-01-23 23:39 UTC, rvernica commented on src/shim.c
> + *  - "Weak" mode with clear_buffer == 0: the output buffer is returned entirely and
To clarify these comments, it seems that _weak_ mode is expressed in code as `clear_buffer == 0`. If so, I would change the comment to say:
```
* - "Weak" mode (clear_buffer == 0):
```
This makes it clear that there is no _weak_ mode with `clear_buffer > 0`.

2023-01-24 00:39 UTC, jwimberl commented on src/shim.c
> -  free (lbuf);
This was an accident and should be reverted, and I'll also double check  the new code paths for leaks/double-frees, in particular on `buf`.

2023-01-24 14:30 UTC, jwimberl commented on src/shim.c
> -  free (lbuf);
Addressed in 89b141010; double checked that all new return paths in read_lines and read_bytes have the same exit behavior as the paths they modified (at least regarding frees and locks; some return without doing `time (&s->time)`, but it looks like that is generally only done on successful returns).

One slightly new type of exit condition has been introduced, though, in which the session is cleaned up after a response to the user, and so the user has not explicitly released the session or received a 50x and may be unaware -- occurring when receiving an error code while truncating the buffer after sending the file. I don't think this should be a problem, and probably would never actually occur without other filesystem errors occurring first, but thought it should be pointed out.

2023-01-24 14:30 UTC, jwimberl commented on src/shim.c
> + *  - "Weak" mode with clear_buffer == 0: the output buffer is returned entirely and
Addressed in 89b141010, here and in similar places in code

2023-01-24 17:51 UTC, ksens commented
This is a greatly needed feature. Thanks @jwimberl !

2023-01-24 19:11 UTC, rvernica commented on src/shim.c
> -  free (lbuf);
Just to clarify, if I remember correctly, `time(&s->time)` is used to update the session time in case we need to clean-up sessions. The oldest session will be discarded if we need a session slot. So, it might be important to update `s->time` to keep the session fresh.

2023-01-25 19:02 UTC, jwimberl commented on src/shim.c
> -  free (lbuf);
I've pushed one small change updating s->time for the read_bytes and read_lines cases where the entire buffer is returned, and presume that this will not affect the approval.

2023-01-25 19:02 UTC, merged